[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
assignment = "Hf2EujMsJotwDcSkTxo2uvfTZtfFQcoLVTKjRvmr6jKz"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/relipa/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
